Test
ILSergeyU/java-filmorate pull request #14
Opened 2024-02-26 19:39 UTC by ILSergeyU

2024-02-27 06:32 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (id <= 0 || userId <= 0) {
Вместо такой проверки можно воспользоваться аннотацией `@Positive`

2024-02-27 06:38 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        film.setMpa(mpaDao.get(film.getMpa().getId()));
Вместо дополнительного запроса к БД mpaDao.get, лучше в запросе filmStorage.get заджойнить фильмы и mpa и объект Mpa создать через new

2024-02-27 06:43 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/film/FilmDbStorage.java
> +
Можно конечно и заселектить после вставки, но на курсе стараются использовать способ с кейхолдером
```
		String sqlQuery = "insert into FILMS (NAME, DESCRIPTION, RELEASE_DATE, DURATION, RATE, MPA_ID) values (?, ?, ?, ?, ?, ?)";

		KeyHolder keyHolder = new GeneratedKeyHolder();
		jdbcTemplate.update(connection -> {
			PreparedStatement stmt = connection.prepareStatement(sqlQuery, new String[]{"FILM_ID"});
			stmt.setString(1, film.getName());
			stmt.setString(2, film.getDescription());
			stmt.setDate(3, Date.valueOf(film.getReleaseDate()));
			stmt.setLong(4, film.getDuration());
			stmt.setLong(5, film.getRate());
			stmt.setLong(6, film.getMpa().getId());
			return stmt;
		}, keyHolder);
		film.setId(keyHolder.getKey().longValue());
```

2024-02-27 06:45 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/film/FilmDbStorage.java
> +        return jdbcTemplate.queryForObject(format(
После  обновления селект уже лишний, т.к. его результат будет совпадать с параметром метода Film film

2024-02-27 06:46 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/film/FilmDbStorage.java
> +        for (Genre genre : genres) {
Вместо цикла и вставки по одной записи лучше использовать пакетную операцию
jdbcTemplate.batchUpdate

https://habr.com/ru/articles/703828/

2024-02-27 06:49 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/film/FilmDbStorage.java
> +                new FilmMapper()
маппинг лучше сделать в виде статического метода, чтобы каждый раз при запросе к БД не создавался новый объект маппера.

2024-02-27 06:50 UTC, VadimZharkov requested changes
Нужно доработать

2024-02-28 12:55 UTC, ILSergeyU commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (id <= 0 || userId <= 0) {
Не коректно исключение отрабатывается если через @Positive

2024-02-28 21:10 UTC, closed without merging