Add friends likes
ILSergeyU/java-filmorate pull request #9
Opened 2024-01-18 14:04 UTC by ILSergeyU

2024-01-22 08:58 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        return Map.of("error", "Ошибка Id",
Лучше перейти на Utf-8 кодировку файлов

2024-01-22 09:00 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +
Добавить метод обработки Throwable в 500 ый статус (INTERNAL_SERVER_ERROR)

2024-01-22 09:01 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public Map<String, String> notId(final IncorrectCountException e) {
Вместо jобезличенной мапы лучше сделать классик ErrorResponse и отдавать его.

2024-01-22 09:03 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>  public class FilmController {
Нужно логирование добавить во все методы контроллеров

2024-01-22 09:04 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +public class ErrorHandler {
Нужно добавить логирование в методы

2024-01-22 09:05 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +            user.setName(user.getName());
Зачем переприсваивать тоже самое

2024-01-22 09:06 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +
А где операции с фильмами?

2024-01-22 09:09 UTC, VadimZharkov requested changes
Нужно исправить замечания

2024-01-23 14:44 UTC, ILSergeyU commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public Map<String, String> notId(final IncorrectCountException e) {
Я не смогу пользоваться методом e.getMessage()
И смогу возвращать только одну ошибку.

2024-01-25 16:10 UTC, ILSergeyU commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        return Map.of("error", "Ошибка Id",
Хорошо

2024-01-25 16:16 UTC, ILSergeyU commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +
Добавил это исключение но. Не прописал, что бы он выбрасывался так как я посчитал что при возникновении Throwable  сам попадет в эту отработку.

2024-01-25 16:31 UTC, ILSergeyU commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +            user.setName(user.getName());
Спасибо, забыл удалить.)

2024-01-25 16:47 UTC, ILSergeyU commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmStorage filmStorage;
Исправил.

2024-01-25 16:48 UTC, ILSergeyU commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +
Исправил.

2024-01-25 17:10 UTC, ILSergeyU commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +public class ErrorHandler {
Исправил

2024-01-26 06:30 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>  public class FilmController {
В контроллер

2024-01-26 06:35 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
>      public Map<String, String> negativeId(final ValidationException e) {
Мар - слишком обезлченный тип. Ты сделал класс ErrorResponse вот в методах обработчика ошибок его и нужно отдавать. Например
```
	@ExceptionHandler
	@ResponseStatus(HttpStatus.NOT_FOUND)
	public ErrorResponse handleNotFoundException(final DataNotFoundException e) {
		log.info("404 {}", e.getMessage());
		return new ErrorResponse(e.getMessage());
	}
```

2024-01-26 06:38 UTC, VadimZharkov requested changes
Можно улучшить

2024-01-26 08:44 UTC, ILSergeyU commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
>      public Map<String, String> negativeId(final ValidationException e) {
Исправил.

2024-01-27 09:01 UTC, VadimZharkov approved these changes

2024-02-20 08:20 UTC, merged